#The intention of this workflow is to run the terraform commands on my mac,
#however it isn't currently functional due to a lack of security credentials on the mac runner

name: initialize-ec2
run-name: initialize-ec2-instance-and-install-nginx
on: workflow_dispatch
jobs:

  ec2-nginx:
    runs-on: ${{ fromJSON('["macos-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}

    steps:
      - uses: actions/checkout@v4
      - run: brew install hashicorp/tap/terraform
      - run: terraform init
      - run: terraform plan
      - run: terraform apply --auto-approve
