name: initialize-ec2
run-name: initialize-ec2-instance-and-install-nginx
on: workflow_dispatch
jobs:

  ec2-nginx:
    runs-on: [self-hosted, macos]
    steps:
      - run: terraform init
      - run: terraform plan
      - run: terraform apply --auto-approve
